services:
  postgres:
    image: postgres:16
    container_name: pocket-postgres
    environment:
      POSTGRES_DB: pocket
      POSTGRES_USER: pocket
      POSTGRES_PASSWORD: pocket
    ports:
      - "5433:5432"
    volumes:
      - pocket-pgdata:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:4-management
    container_name: pocket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pocket-pgdata: