spring:
  application:
    name: pocket
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/pocket}
    username: ${DATABASE_USERNAME:pocket}
    password: ${DATABASE_PASSWORD:pocket}
  flyway:
    enabled: true