spring:
  application:
    name: pocket
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/pocket}
    username: ${DATABASE_USERNAME:pocket}
    password: ${DATABASE_PASSWORD:pocket}
  flyway:
    enabled: true
  rabbitmq:
    addresses: ${RABBITMQ_URL:amqp://guest:guest@localhost:5672}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          multiplier: 2.0
          max-retries: 4
          max-interval: 20000

jwt:
  secret: ${JWT_SECRET:please-dont-hack-my-broke-student-wallet-app}
  expiration-ms: 900000

plaid:
  client-id: ${PLAID_CLIENT_ID:}
  secret: ${PLAID_SECRET:}

logging:
  level:
    org.springframework.security: DEBUG